apiVersion: v1
kind: Service
metadata:
  name: {{ include "di.service" (dict "root" . "component" "backend") }}
  labels:
    {{- include "di.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "di.selector" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      {{- with .Values.backend.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
