{{- $name := include "di.service" (dict "root" . "component" "prometheus") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "di.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  labels:
    {{- include "di.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [endpoints, pods, services]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  labels:
    {{- include "di.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
