apiVersion: v1
kind: Pod

metadata:
  name: curl-client
  namespace: devops-insights

spec:
  containers:
    - name: curl
      image: curlimages/curl:8.18.0
      command:
        - /bin/sh
        - -c
        - |
          sleep 3600
