apiVersion: v1
kind: Pod

metadata:
  name: storage-test
  namespace: devops-insights

spec:
  containers:
    - name: storage-test
      image: busybox:1.37

      command:
        - /bin/sh
        - -c
        - |
          sleep 3600

      volumeMounts:
        - name: storage-test-data
          mountPath: /data

  volumes:
    - name: storage-test-data
      persistentVolumeClaim:
        claimName: storage-test-data